"""empty message

Revision ID: 07e905c505d7
Revises: 5485a55bd01b
Create Date: 2025-01-11 20:38:21.050064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07e905c505d7'
down_revision = '5485a55bd01b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_comments', schema=None) as batch_op:
        batch_op.alter_column('create_date',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.alter_column('deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.alter_column('deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('blog_comments', schema=None) as batch_op:
        batch_op.alter_column('deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('create_date',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
