"""empty message

Revision ID: 3e758d88f77f
Revises: 722b85321ecc
Create Date: 2025-01-06 18:44:10.603053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e758d88f77f'
down_revision = '722b85321ecc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # Add the 'type' column with a default value to existing rows
        op.add_column('users', sa.Column('type', sa.String(50), nullable=True))
        
        # Now populate the 'type' column for all existing rows with a default value
        op.execute("UPDATE users SET type = gen_random_uuid()")  # You can use `gen_random_uuid()` or some other value.
        
        # Alter the column to make it NOT NULL
        op.alter_column('users', 'type', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('type')

    # ### end Alembic commands ###
