"""empty message

Revision ID: 48a27bf9c51f
Revises: b93c75c02b8e
Create Date: 2024-11-07 01:08:40.000949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48a27bf9c51f'
down_revision = 'b93c75c02b8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ressources', schema=None) as batch_op:
        batch_op.alter_column('private',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('admin')

    with op.batch_alter_table('ressources', schema=None) as batch_op:
        batch_op.alter_column('private',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
