"""empty message

Revision ID: 50be9d723d50
Revises: 9ea5f085ca21
Create Date: 2024-11-10 21:06:05.276287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50be9d723d50'
down_revision = '9ea5f085ca21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('newsletter_subs')
    with op.batch_alter_table('air_nomads', schema=None) as batch_op:
        batch_op.drop_column('confirmed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('air_nomads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed', sa.INTEGER(), autoincrement=False, nullable=False))

    op.create_table('newsletter_subs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('confirmed', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='newsletter_subs_pkey'),
    sa.UniqueConstraint('email', name='newsletter_subs_email_key'),
    sa.UniqueConstraint('token', name='newsletter_subs_token_key')
    )
    # ### end Alembic commands ###
