"""empty message

Revision ID: 54764518d7ef
Revises: 6e16e02b47bc
Create Date: 2024-11-04 16:58:03.195535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54764518d7ef'
down_revision = '6e16e02b47bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('confirmed',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('token',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('confirmed',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)

    # ### end Alembic commands ###
