"""empty message

Revision ID: 6273bf7f60fc
Revises: 4db18c165161
Create Date: 2024-11-06 15:42:39.786447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6273bf7f60fc'
down_revision = '4db18c165161'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ressources', schema=None) as batch_op:
        batch_op.drop_column('votes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ressources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('votes', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
