"""empty message

Revision ID: 66eead5f3daf
Revises: c6e2e6dc6f61
Create Date: 2025-09-18 15:54:14.566782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66eead5f3daf'
down_revision = 'c6e2e6dc6f61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('air_nomads', sa.Column('excluded_countries', sa.String(), server_default='', nullable=False))
    op.add_column('air_nomads', sa.Column('min_days_ahead', sa.Integer(), server_default='1', nullable=False))
    op.add_column('air_nomads', sa.Column('max_days_ahead', sa.Integer(), server_default='182', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('air_nomads', 'max_days_ahead')
    op.drop_column('air_nomads', 'min_days_ahead')
    op.drop_column('air_nomads', 'excluded_countries')
    # ### end Alembic commands ###
