"""empty message

Revision ID: 70304b9d4f4f
Revises: 66eead5f3daf
Create Date: 2025-09-18 16:10:39.147170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70304b9d4f4f'
down_revision = '66eead5f3daf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('air_nomads', 'excluded_countries')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('air_nomads', sa.Column('excluded_countries', sa.VARCHAR(), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
