"""empty message

Revision ID: 82d3de736413
Revises: 427c4fc56fd5
Create Date: 2024-11-04 22:50:00.415420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82d3de736413'
down_revision = '427c4fc56fd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('top_movies', schema=None) as batch_op:
        batch_op.drop_constraint('top_movies_title_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('top_movies', schema=None) as batch_op:
        batch_op.create_unique_constraint('top_movies_title_key', ['title'])

    # ### end Alembic commands ###
