"""empty message

Revision ID: 849f0ad85a83
Revises: 78fd371919cf
Create Date: 2025-01-16 21:04:09.575309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '849f0ad85a83'
down_revision = '78fd371919cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edited', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_comments', schema=None) as batch_op:
        batch_op.drop_column('edited')

    # ### end Alembic commands ###
