"""empty message

Revision ID: a9ac03c1d07f
Revises: 340ca78a9ac1
Create Date: 2024-11-07 01:30:02.503651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9ac03c1d07f'
down_revision = '340ca78a9ac1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ressources', schema=None) as batch_op:
        batch_op.alter_column('private',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('ressources', schema=None) as batch_op:
        batch_op.alter_column('private',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
