"""empty message

Revision ID: af2753781b80
Revises: 3bb3300737f2
Create Date: 2024-11-05 21:37:31.147106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af2753781b80'
down_revision = '3bb3300737f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ressources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('added', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ressources', schema=None) as batch_op:
        batch_op.drop_column('added')

    # ### end Alembic commands ###
