"""empty message

Revision ID: b54c8e2a1cc5
Revises: 6e6ae98397a2
Create Date: 2024-11-05 20:51:27.901342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b54c8e2a1cc5'
down_revision = '6e6ae98397a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ressources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('medium', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('votes', sa.Integer(), nullable=False),
    sa.Column('tags', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    op.drop_table('ressources')
    # ### end Alembic commands ###
