"""empty message

Revision ID: b7fc727ff767
Revises: 73682b41042b
Create Date: 2025-01-07 01:14:10.793931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7fc727ff767'
down_revision = '73682b41042b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=False))
        batch_op.drop_column('time')

    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=False))
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.drop_column('deleted')
        batch_op.drop_column('create_date')

    with op.batch_alter_table('blog_comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('deleted')
        batch_op.drop_column('create_date')

    # ### end Alembic commands ###
