"""empty message

Revision ID: df5f008e7c68
Revises: 70304b9d4f4f
Create Date: 2025-09-18 16:12:27.171531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df5f008e7c68'
down_revision = '70304b9d4f4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('air_nomads', sa.Column('excluded_countries', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('air_nomads', 'excluded_countries')
    # ### end Alembic commands ###
