"""empty message

Revision ID: e6ed03119385
Revises: 849f0ad85a83
Create Date: 2025-01-16 21:46:10.932570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6ed03119385'
down_revision = '849f0ad85a83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_comments', schema=None) as batch_op:
        batch_op.alter_column('edited',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.alter_column('is_draft',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('tags',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('ressources', schema=None) as batch_op:
        batch_op.alter_column('private',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('ressources', schema=None) as batch_op:
        batch_op.alter_column('private',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.alter_column('tags',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('is_draft',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('blog_comments', schema=None) as batch_op:
        batch_op.alter_column('edited',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
