"""empty message

Revision ID: fa1bc1dc0e2b
Revises: 48a27bf9c51f
Create Date: 2024-11-07 01:09:19.144998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa1bc1dc0e2b'
down_revision = '48a27bf9c51f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ressources', schema=None) as batch_op:
        batch_op.alter_column('private',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('admin')

    with op.batch_alter_table('ressources', schema=None) as batch_op:
        batch_op.alter_column('private',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
